''
'' A dark blue style from "Red Dress"
''
'' Original Author: https://github.com/Drakemor
'' https://github.com/Drakemor/RedDress-PlantUML
''

!$THEME = "reddress-darkblue"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

!if (%not(%variable_exists("$FONTNAME")))
!$FONTNAME = "Verdana"
!endif

!if (%not(%variable_exists("$FONTSIZE")))
!$FONTSIZE = 11
!endif

!$BOXBG = "2e2e2e"
!$BORDERCOLOR = "1b1b1b"
!$LIGHTBG = "575757"
!$LIGHTBORDERCOLOR = "767676"

!$ACCENT = "1a66c2"
!$ACCENT_T10 = "1a66c219"
!$ACCENT_T20 = "1a66c233"
!$ACCENT_T30 = "1a66c24D"
!$ACCENT_T40 = "1a66c266"
!$ACCENT_T50 = "1a66c280"
!$ACCENT_DARK = "002642"

!$PRIMARYFONTCOLOR = "FFFFFF"
!$SECONDARYFONTCOLOR = "AAAAAA"
!$LIGHTFONTCOLOR = "000000"

!$ARROWCOLOR = "FFFFFF"
!$ARROWFONTCOLOR = "BBBBBB"

!$SUCCESS = "#4CAF50"
!$WARNING = "#ff9800"
!$DANGER = "#F44336"

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'' Procedures
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

!procedure $success($msg)
  <font color=$SUCCESS><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$DANGER><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$WARNING><b>$msg
!endprocedure

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'' Style Settings
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

<style>
  root {
    FontColor $PRIMARYFONTCOLOR
    FontName $FONTNAME
    FontSize $FONTSIZE
    Margin 4
    RoundCorner 8
    shadowing 2
  }
  document {
    BackgroundColor $BGCOLOR
    HyperLinkColor $PRIMARYFONTCOLOR
    title {
      BackgroundColor $ACCENT_T50 
      LineColor $WHITE
      FontSize 16
    }
  }
  node {
    BackgroundColor $BOXBG
    LineColor $BORDERCOLOR
    FontColor $PRIMARYFONTCOLOR
    RoundCorner 0
    LineThickness 2
    separator {
      LineThickness 0.5
      LineColor $LIGHTBORDERCOLOR
    }
  }
  note {
    StereotypeFontColor $SECONDARYFONTCOLOR
    StereotypeFontSize $FONTSIZE
    BackgroundColor $ACCENT
    BorderColor $ACCENT_DARK
  }
  
  arrow {
    BackGroundColor lightblue
    FontColor $ARROWFONTCOLOR
    LineColor $ARROWCOLOR
    LineThickness 2
    LineStyle 0
  }
  highlight {
    BackGroundColor $ACCENT_T50
    FontStyle italic
  }

  json, object, map {
    BackgroundColor $BOXBG
    FontColor $SECONDARYFONTCOLOR
  }

activityDiagram {
  partition, group, package {
    Shadowing 0
    BackgroundColor #$ACCENT_T20
    LineColor $ACCENT_DARK
    Title {
      FontStyle bold
    }
  }
  activity {
    BackgroundColor $BOXBG
    BorderColor $BORDERCOLOR
  }
  diamond, circle {
    BackgroundColor $LIGHTBG
    BorderColor $BORDERCOLOR
  }
  start {
    BackgroundColor $SUCCESS
    LineColor $LIGHTBORDERCOLOR
  }
  stop, end {
    Shadowing 0
    BackgroundColor $DANGER
    LineColor $DANGER
  }
  activityBar {
    Shadowing 0
    BackgroundColor $WHITE
    LineColor $WHITE
    BorderColor $WHITE
  }
  swimlane {
    BackgroundColor $ACCENT_DARK
    LineColor $ACCENT_DARK
  }
}

classDiagram {
  class {
    LineThickness 2
    LineColor $BORDERCOLOR
    BackgroundColor $BOXBG
    FontColor $SECONDARYFONTCOLOR
    generic {
      BackgroundColor $LIGHTBG
      FontColor $SECONDARYFONTCOLOR
    }
    stereotype {
      BackgroundColor $DANGER
    }
  }
  stereotype {
    BackgroundColor $ACCENT
    FontColor $SECONDARYFONTCOLOR
    FontSize $FONTSIZE
    
  }
  package {
    Shadowing 0
    BackgroundColor #$ACCENT_T20
    LineColor $ACCENT_DARK
    Title {
      FontStyle bold
    }
    
  }
  diamond, interface {
    LineColor $BORDERCOLOR
    BackgroundColor $LIGHTBG
    Shadowing 0
  }
}

jsonDiagram, yamlDiagram {
  arrow {
    LineThickness 2
    LineStyle 5,5
  }
  node {
    maximumWidth 256
  }
}

timingDiagram {
  highlight {
    BackgroundColor $BOXBG
    FontColor $PRIMARYFONTCOLOR
    LineColor $LIGHTBORDERCOLOR
  }
  concise {
    LineThickness 4
    LineColor $ACCENT
    BackgroundColor transparent
    FontColor $PRIMARYFONTCOLOR
  }
  process {
    BackgroundColor $DANGER
  }
  constraintArrow {
    LineThickness 2
    LineColor $DANGER
  }
  analog {
    LineThickness 2
    LineColor $WARNING
  }
  clock, binary, robust {
    LineThickness 2
    LineColor $SUCCESS
  }
}

ganttDiagram {
  undone {
    BackgroundColor $LIGHTBG
  }
  task {
    BackgroundColor $SUCCESS
    LineColor $BORDERCOLOR
    RoundCorner 0
    FontColor $PRIMARYFONTCOLOR
    unstarted {
      BackgroundColor $DANGER
    }
  }
  closed {
    BackgroundColor $ACCENT_T50
  }
  timeline {
    BackgroundColor $BOXBG
    LineColor $LIGHTBORDERCOLOR
  }
  milestone {
    BackgroundColor $ACCENT
  }
  separator {
    LineColor $LIGHTBORDERCOLOR
    BackgroundColor transparent
    FontStyle bold
  }
  verticalSeparator {
    LineColor $LIGHTBORDERCOLOR
    LineThickness 3
    LineSTyle 4, 4
  }
  quarter {
    BackgroundColor $DANGER
  }
  region {
    BackgroundColor $DANGER
  }
}

sequenceDiagram {
  Start, End {
    FontColor $PRIMARYFONTCOLOR
  }
  Box {
    BackgroundColor $ACCENT_DARK
    LineColor $BORDERCOLOR
    FontColor $PRIMARYFONTCOLOR
  }
  Delay {
    LineColor $BORDERCOLOR
    FontColor $SECONDARYFONTCOLOR
  }
  LifeLine {
    Shadowing 0
    BackgroundColor $LIGHTBG
    LineColor $LIGHTBORDERCOLOR
    LineThickness 1
  }
  Divider {
    BackgroundColor $ACCENT
    LineColor $BORDERCOLOR
    LineThickness 2
    FontColor $PRIMARYFONTCOLOR
  }
  GroupHeader {
    BackgroundColor $ACCENT
    LineColor $ACCENT_DARK
    FontColor $PRIMARYFONTCOLOR
  }
  Group {
    Shadowing 0
    BackgroundColor $ACCENT_T20
    LineColor $ACCENT_DARK
    FontColor $SECONDARYFONTCOLOR
  }
  ReferenceHeader {
    BackgroundColor $ACCENT_DARK
    LineColor $BORDERCOLOR
    FontColor $PRIMARYFONTCOLOR
  }
  Reference {
    Shadowing 0
    LineColor $BORDERCOLOR
    BackgroundColor $ACCENT_DARK
    FontColor $SECONDARYFONTCOLOR
  }
  Separator {
    BackgroundColor $ACCENT
  }
  actor, database, boundary, entity, collections, participant, control {
    
    BackgroundColor $BOXBG
    LineColor $BORDERCOLOR
  }
  actor {
    LineThickness 2
  }
}

stateDiagram {
  state {
    BackgroundColor $BOXBG
    LineColor $BORDERCOLOR
  }
  stateBody {
    BackgroundColor $ACCENT_T20
    LineColor $BORDERCOLOR
  }
  diamond, circle {
    BackgroundColor $LIGHTBG
    LineColor $BORDERCOLOR
  }
  start {
    BackgroundColor $SUCCESS
    LineColor $LIGHTBORDERCOLOR
  }
  end {
    Shadowing 0
    BackgroundColor $DANGER
    LineColor $DANGER
  }
}
</style>