''
'' A dark blue style from "Red Dress"
''
'' Original Author: https://github.com/Drakemor
'' https://github.com/Drakemor/RedDress-PlantUML
''

!$THEME = "reddress-darkblue"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

!if (%not(%variable_exists("$FONTNAME")))
!$FONTNAME = "Verdana"
!endif

!if (%not(%variable_exists("$FONTSIZE")))
!$FONTSIZE = 11
!endif

!$BOXBG = "2e2e2e"
!$LIGHTBG = "575757"

!$ACCENT = "1a66c2"
!$ACCENT_T10 = "1a66c219"
!$ACCENT_T20 = "1a66c233"
!$ACCENT_T30 = "1a66c24D"
!$ACCENT_T40 = "1a66c266"
!$ACCENT_T50 = "1a66c280"
!$ACCENT_DARK = "002642"

!$BORDERCOLOR = "1b1b1b"
!$LIGHTBORDERCOLOR = "767676"

!$PRIMARYFONTCOLOR = "FFFFFF"
!$SECONDARYFONTCOLOR = "AAAAAA"
!$LIGHTFONTCOLOR = "000000"

!$ARROWCOLOR = "FFFFFF"
!$ARROWFONTCOLOR = "BBBBBB"

!$SUCCESS = "#4CAF50"
!$WARNING = "#ff9800"
!$DANGER = "#F44336"

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'' Global Values
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

skinparam backgroundColor $BGCOLOR
skinparam stereotypeCBackgroundColor $ACCENT

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'' Procedures
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

!procedure $success($msg)
  <font color=$SUCCESS><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$DANGER><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$WARNING><b>$msg
!endprocedure

!procedure basic_style()
  fontColor $PRIMARYFONTCOLOR
  fontName $FONTNAME
  fontSize $FONTSIZE
  stereotypeFontColor $SECONDARYFONTCOLOR
  stereotypeFontSize $FONTSIZE
  backgroundColor $BOXBG
  borderColor $BORDERCOLOR
!endprocedure

!procedure light_style()
  backgroundColor $LIGHTBG
  borderColor $LIGHTBORDERCOLOR
!endprocedure

!procedure accent_style()
  backgroundColor $ACCENT
  borderColor $ACCENT_DARK
!endprocedure

!procedure arrow_style()
  arrowColor $ARROWCOLOR
  arrowFontName $FONTNAME
  arrowFontColor $ARROWFONTCOLOR
  arrowFontSize $FONTSIZE
!endprocedure

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'' Style Settings
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

<style>
  root {
    BackGroundColor $BGCOLOR
    FontColor $PRIMARYFONTCOLOR
  }
  node {
    BackGroundColor $BOXBG
    LineColor $BORDERCOLOR
    FontName $FONTNAME
    FontColor $PRIMARYFONTCOLOR
    FontSize $FONTSIZE
    RoundCorner 0
    LineThickness 2
    separator {
      LineThickness 0.5
      LineColor $LIGHTBORDERCOLOR
    }
  }
  note {
    FontColor $PRIMARYFONTCOLOR
	FontName $FONTNAME
	fontSize $FONTSIZE
    StereotypeFontColor $SECONDARYFONTCOLOR
    StereotypeFontSize $FONTSIZE
    BackgroundColor $ACCENT
    BorderColor $ACCENT_DARK
  }

  arrow {
    BackGroundColor lightblue
    FontColor $ARROWFONTCOLOR
    LineColor $ARROWCOLOR
    LineThickness 2
    LineStyle 0
  }
  highlight {
    BackGroundColor $ACCENT
    FontColor $PRIMARYFONTCOLOR
    FontStyle italic
  }
  activityDiagram {
    partition {
      Shadowing 0
      BackgroundColor #$ACCENT_T20
      LineColor $ACCENT_DARK
    }
    group {
      Shadowing 0
      BackgroundColor #$ACCENT_T20
      LineColor $ACCENT_DARK
    }
    package {
      Shadowing 0
      BackgroundColor #$ACCENT_T20
      LineColor $ACCENT_DARK
    }
    activity {
      BackgroundColor $BOXBG
      BorderColor $BORDERCOLOR
	  FontColor $PRIMARYFONTCOLOR
    }
    diamond {
      BackgroundColor $LIGHTBG
  	  BorderColor $BORDERCOLOR
	  FontColor $PRIMARYFONTCOLOR
    }
	circle {
      BackgroundColor $LIGHTBG
      LineColor $BORDERCOLOR
    }
    start {
      BackgroundColor $SUCCESS
      LineColor $LIGHTBORDERCOLOR
    }
    stop, end {
      Shadowing 0
      BackgroundColor $DANGER
      LineColor $DANGER
    }

    activityBar {
	  Shadowing 0
	  BackgroundColor $WHITE
	  LineColor $WHITE
	  BorderColor $WHITE
    }
  }
</style>


' Class diagrams

skinparam circledCharacter {
  radius 8
  fontSize $FONTSIZE
  fontName $FONTNAME
}

skinparam class {
  basic_style()
  arrow_style()

  attributeFontColor $SECONDARYFONTCOLOR
  attributeFontSize $FONTSIZE
  attributeIconSize $FONTSIZE
}

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'' Sequence diagrams
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
!startsub sequence

skinparam sequence {
	BorderColor $BORDERCOLOR
	' For some reason sequence title font color does not pick up from global
	TitleFontColor $PRIMARYFONTCOLOR
	StartColor $PRIMARYFONTCOLOR
	EndColor $PRIMARYFONTCOLOR
	''
	BoxBackgroundColor $LIGHTBG
	BoxBorderColor $BORDERCOLOR
	BoxFontColor $PRIMARYFONTCOLOR
	''
	DelayFontColor $SECONDARYFONTCOLOR
	''
	LifeLineBorderColor $ARROWCOLOR
	LifeLineBorderThickness 2
	LifeLineBackgroundColor $BORDERCOLOR
	''
	GroupBorderColor $BORDERCOLOR
	GroupBackgroundColor $ACCENT
	GroupFontColor $SECONDARYFONTCOLOR
	GroupHeaderFontColor $PRIMARYFONTCOLOR
	''
	DividerBackgroundColor $ACCENT
    DividerBorderColor $BORDERCOLOR
    DividerBorderThickness 2
    DividerFontColor $PRIMARYFONTCOLOR
	''
	ReferenceBackgroundColor $ACCENT_DARK
	ReferenceBorderColor $BORDERCOLOR
	ReferenceFontColor $PRIMARYFONTCOLOR
	ReferenceHeaderFontColor $PRIMARYFONTCOLOR
	''
	StereotypeFontColor $PRIMARYFONTCOLOR
}
!endsub

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'' Activity diagrams
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
skinparam actor {
  basic_style()
  accent_style()
}

skinparam participant {
  basic_style()
}

skinparam collections {
  basic_style()
}

' Component diagrams

skinparam interface {
  basic_style()
  accent_style()
}

skinparam component {
  basic_style()
}

skinparam node {
  basic_style()
}

skinparam database {
  basic_style()
}

skinparam queue {
  basic_style()
}

' Use Case diagrams

skinparam usecase {
  basic_style()
  arrow_style()
}

skinparam boundary {
  basic_style()
  accent_style()
}

skinparam control {
  basic_style()
  accent_style()
}

skinparam entity {
  basic_style()
  accent_style()
}

' State diagrams

skinparam state {
  basic_style()
  arrow_style()
  startColor $ACCENT
  endColor $ACCENT_DARK
}

' Object diagrams

skinparam object {
  basic_style()
  arrow_style()
}

' Common
skinparam cloud {
  basic_style()
  arrow_style()
}

skinparam rectangle {
  basic_style()
}

skinparam storage {
  basic_style()
}